/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapa.java.i;

/**
 *
 * @author jair
 */
public class GameScore extends javax.swing.JFrame {

    /**
     * Creates new form GameScore
     */
    public GameScore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warning = new java.awt.PopupMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        placarB = new java.awt.TextField();
        placarA = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pontosA = new java.awt.TextField();
        Pontos = new javax.swing.JLabel();
        pontosB = new java.awt.TextField();
        menosTimeA = new javax.swing.JButton();
        maisTimeA = new javax.swing.JButton();
        mais3TimeA = new javax.swing.JButton();
        menosTimeB = new javax.swing.JButton();
        maisTimeB = new javax.swing.JButton();
        mais3TimeB = new javax.swing.JButton();
        vencedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resetarPontos = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        placar = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        warning.setLabel("Aviso");
        warning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        placarB.setText("0");
        placarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placarBActionPerformed(evt);
            }
        });

        placarA.setText("0");
        placarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placarAActionPerformed(evt);
            }
        });

        jLabel1.setText("Time B");

        jLabel2.setText("Time A");

        pontosA.setText("0");
        pontosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontosAActionPerformed(evt);
            }
        });

        Pontos.setText("Pontos");

        pontosB.setText("0");
        pontosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontosBActionPerformed(evt);
            }
        });

        menosTimeA.setText("-1");
        menosTimeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosTimeAActionPerformed(evt);
            }
        });

        maisTimeA.setText("+1");
        maisTimeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisTimeAActionPerformed(evt);
            }
        });

        mais3TimeA.setText("+3");
        mais3TimeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mais3TimeAActionPerformed(evt);
            }
        });

        menosTimeB.setText("-1");
        menosTimeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosTimeBActionPerformed(evt);
            }
        });

        maisTimeB.setText("+1");
        maisTimeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisTimeBActionPerformed(evt);
            }
        });

        mais3TimeB.setText("+3");
        mais3TimeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mais3TimeBActionPerformed(evt);
            }
        });

        vencedor.setText("X");
        vencedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vencedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Vencedor");

        resetarPontos.setForeground(java.awt.Color.orange);
        resetarPontos.setText("Recomecar a Partida");
        resetarPontos.setActionCommand("");
        resetarPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarPontosActionPerformed(evt);
            }
        });

        restart.setBackground(new java.awt.Color(248, 241, 241));
        restart.setForeground(new java.awt.Color(251, 12, 24));
        restart.setText("Recomecar Jogo");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        placar.setText("Placar");

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Placar Jair -Jogo de Cartas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menosTimeB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mais3TimeB)
                            .addComponent(maisTimeB)
                            .addComponent(pontosB, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(placarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menosTimeA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mais3TimeA)
                                    .addComponent(maisTimeA)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(placar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pontos))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(7, 7, 7)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(placarA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pontosA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(168, 168, 168)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(resetarPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vencedor)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(placar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addComponent(Pontos)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pontosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pontosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menosTimeA)
                            .addComponent(maisTimeA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mais3TimeA))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menosTimeB)
                            .addComponent(maisTimeB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mais3TimeB)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(resetarPontos)
                        .addGap(18, 18, 18)
                        .addComponent(restart))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        label1.getAccessibleContext().setAccessibleName("Placar Jair -Jogo de Cartas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placarBActionPerformed

    private void placarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placarAActionPerformed

    private void pontosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontosAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontosAActionPerformed

    private void pontosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontosBActionPerformed

    private void maisTimeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisTimeAActionPerformed
        int actualPointsA = Integer.parseInt(pontosA.getText());
        actualPointsA+=1;
        checkPoints("A", actualPointsA);
        
    }//GEN-LAST:event_maisTimeAActionPerformed
    private void checkPoints(String team, int points){

        if (team.equals("A")){
            pontosA.setText(String.valueOf(points));
        }
        else{
            pontosB.setText(String.valueOf(points));
        }
        
        if (points>=12){
                pontosA.setText("0");
                pontosB.setText("0");
                checkPlacar(team); 
            }
    }
    
    private void checkPlacar(String team){
        int placarAtual;
        if (team.equals("A")){
            placarAtual = Integer.parseInt(placarA.getText());
            placarAtual+=1;
            placarA.setText(String.valueOf(placarAtual));
        }
        else{
            placarAtual = Integer.parseInt(placarB.getText());
            placarAtual+=1;
            placarB.setText(String.valueOf(placarAtual));
        }
        
        if (placarAtual>=3){
            vencedor.setText("O vencedor é o Time "+team+".");
            mais3TimeA.setEnabled(false);
            mais3TimeB.setEnabled(false);
            menosTimeA.setEnabled(false);
            menosTimeB.setEnabled(false);
            maisTimeA.setEnabled(false);
            maisTimeB.setEnabled(false);
            resetarPontos.setEnabled(false);
        }    
    }
    private void mais3TimeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mais3TimeAActionPerformed
        int actualPointsA = Integer.parseInt(pontosA.getText());
        actualPointsA+=3;
        checkPoints("A", actualPointsA);
    }//GEN-LAST:event_mais3TimeAActionPerformed

    private void maisTimeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisTimeBActionPerformed
        int actualPointsB = Integer.parseInt(pontosB.getText());
        actualPointsB+=1;
        checkPoints("B", actualPointsB);
    }//GEN-LAST:event_maisTimeBActionPerformed

    private void mais3TimeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mais3TimeBActionPerformed
        int actualPointsB = Integer.parseInt(pontosB.getText());
        actualPointsB+=3;
        checkPoints("B", actualPointsB);
    }//GEN-LAST:event_mais3TimeBActionPerformed

    private void vencedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vencedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vencedorActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        placarA.setText("0");
        placarB.setText("0");
        vencedor.setText("X");
        mais3TimeA.setEnabled(true);
        mais3TimeB.setEnabled(true);
        menosTimeA.setEnabled(true);
        menosTimeB.setEnabled(true);
        maisTimeA.setEnabled(true);
        maisTimeB.setEnabled(true);
        resetarPontos.setEnabled(true);
    }//GEN-LAST:event_restartActionPerformed

    private void menosTimeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosTimeAActionPerformed
        int actualPoints = Integer.parseInt(pontosA.getText());
        if (actualPoints > 0){
            actualPoints-=1;
            pontosA.setText(String.valueOf(actualPoints));
        }
    }//GEN-LAST:event_menosTimeAActionPerformed

    private void menosTimeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosTimeBActionPerformed
        int actualPoints = Integer.parseInt(pontosA.getText());
        if (actualPoints > 0){
            actualPoints-=1;
            pontosB.setText(String.valueOf(actualPoints));
        }
    }//GEN-LAST:event_menosTimeBActionPerformed

    private void resetarPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarPontosActionPerformed
        if (Integer.parseInt(placarA.getText()) <3 && Integer.parseInt(placarA.getText())<3){
            pontosA.setText("0");
            pontosB.setText("0");
        }
        else{
            AvisoGame dialog = new AvisoGame(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_resetarPontosActionPerformed

    private void warningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pontos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private javax.swing.JButton mais3TimeA;
    private javax.swing.JButton mais3TimeB;
    private javax.swing.JButton maisTimeA;
    private javax.swing.JButton maisTimeB;
    private javax.swing.JButton menosTimeA;
    private javax.swing.JButton menosTimeB;
    private javax.swing.JLabel placar;
    private java.awt.TextField placarA;
    private java.awt.TextField placarB;
    private java.awt.TextField pontosA;
    private java.awt.TextField pontosB;
    private javax.swing.JButton resetarPontos;
    private javax.swing.JButton restart;
    private javax.swing.JTextField vencedor;
    private java.awt.PopupMenu warning;
    // End of variables declaration//GEN-END:variables
}
